name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # Hourly sync
  workflow_dispatch: # Manual trigger option

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the forked repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/Reloisback/Whiteout-Survival-Discord-Bot.git
          git fetch upstream

      - name: Merge changes from upstream
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
